---
- name: deploy vm from template
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  #pre_tasks:
  #  - include_vars: vars.yaml
  tasks:
    - name: clone VM
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        folder: "{{ vm_destination_folder }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        cluster: "{{ vcenter_cluster }}"
        disk:
          - datastore: "{{ vcenter_datastore }}"
            type: thin
            size_gb: "{{ vm_disk_size }}"
        hardware:
          memory_mb: "{{ vm_memory_size }}"
          num_cpus: "{{ vm_cpu_socket }}"
          #num_cpu_cores_per_socket: "{{ vm_cpu_cores_per_socket }}"
          scsi: paravirtual
        networks:
          - name: "{{ vm_network_name }}"
            connected: yes
            type: dhcp
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        state: "{{ vm_state }}"
